apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastapi-svc
  name: fastapi-svc
spec:
  selector:
    app: fastapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
    nodePort: 31110
  type: NodePort